BEGIN;

CREATE TABLE IF NOT EXISTS user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    password_salt TEXT NOT NULL,
    full_name TEXT,
    role TEXT NOT NULL CHECK (role IN ('admin', 'manager', 'user')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    password_changed_at TIMESTAMPTZ,
    password_expires_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_user_accounts_role ON user_accounts(role);
CREATE INDEX IF NOT EXISTS idx_user_accounts_is_active ON user_accounts(is_active);

CREATE TABLE IF NOT EXISTS user_job_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
    job_no TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_user_job_access_user_job UNIQUE (user_id, job_no)
);

CREATE INDEX IF NOT EXISTS idx_user_job_access_user_id ON user_job_access(user_id);
CREATE INDEX IF NOT EXISTS idx_user_job_access_job_no ON user_job_access(job_no);

CREATE TABLE IF NOT EXISTS user_sessions (
    token TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id ON user_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_sessions_expires_at ON user_sessions(expires_at);

CREATE TABLE IF NOT EXISTS download_tasks (
    task_id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
    task_type TEXT NOT NULL,
    request_params JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    progress INTEGER NOT NULL DEFAULT 0,
    total_files INTEGER NOT NULL DEFAULT 0,
    processed_files INTEGER NOT NULL DEFAULT 0,
    zip_path TEXT,
    zip_size BIGINT,
    error_message TEXT,
    warning_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_download_tasks_user_id ON download_tasks(user_id);
CREATE INDEX IF NOT EXISTS idx_download_tasks_status ON download_tasks(status);
CREATE INDEX IF NOT EXISTS idx_download_tasks_created_at ON download_tasks(created_at);
CREATE INDEX IF NOT EXISTS idx_download_tasks_expires_at ON download_tasks(expires_at);

CREATE TABLE IF NOT EXISTS pdf_tasks (
    task_id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
    order_no BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    progress INTEGER NOT NULL DEFAULT 0,
    message TEXT,
    pdf_path TEXT,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_pdf_tasks_user_id ON pdf_tasks(user_id);
CREATE INDEX IF NOT EXISTS idx_pdf_tasks_order_no ON pdf_tasks(order_no);
CREATE INDEX IF NOT EXISTS idx_pdf_tasks_status ON pdf_tasks(status);
CREATE INDEX IF NOT EXISTS idx_pdf_tasks_created_at ON pdf_tasks(created_at);

CREATE TABLE IF NOT EXISTS "PDF_Status" (
    "Order_No" BIGINT PRIMARY KEY,
    pdf_status TEXT NOT NULL DEFAULT 'pending',
    pdf_path TEXT,
    generated_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pdf_status_status ON "PDF_Status"(pdf_status);
CREATE INDEX IF NOT EXISTS idx_pdf_status_updated_at ON "PDF_Status"(updated_at);

CREATE TABLE IF NOT EXISTS file_index_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path TEXT NOT NULL UNIQUE,
    file_name TEXT NOT NULL,
    folder_path TEXT NOT NULL,
    folder_type TEXT NOT NULL CHECK (
        folder_type IN (
            'Stockist Cert',
            'Private Formal',
            'Private Prelim',
            'IAT Formal',
            'IAT Prelim'
        )
    ),
    file_size BIGINT,
    modified_time DOUBLE PRECISION,
    created_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_checked TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    extracted_keywords TEXT,
    identifiers TEXT,
    file_hash TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_file_index_cache_file_path ON file_index_cache(file_path);
CREATE INDEX IF NOT EXISTS idx_file_index_cache_folder_type_file_name ON file_index_cache(folder_type, file_name);
CREATE INDEX IF NOT EXISTS idx_file_index_cache_last_checked ON file_index_cache(last_checked);
CREATE INDEX IF NOT EXISTS idx_file_index_cache_folder_type ON file_index_cache(folder_type);
CREATE INDEX IF NOT EXISTS idx_file_index_cache_is_deleted ON file_index_cache(is_deleted);
CREATE INDEX IF NOT EXISTS idx_file_index_cache_identifiers ON file_index_cache(identifiers);

CREATE TABLE IF NOT EXISTS file_index_metadata (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO file_index_metadata (key, value)
VALUES
    ('last_full_scan', ''),
    ('total_files_indexed', '0'),
    ('index_version', '1.0'),
    ('scan_status', 'idle')
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS bbs_dd (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bbs_no BIGINT NOT NULL,
    jobsite_no TEXT,
    dd_no TEXT,
    dd_delivery_date DATE,
    order_desc TEXT,
    jobsite_type TEXT
);

CREATE INDEX IF NOT EXISTS idx_bbs_dd_bbs_no ON bbs_dd(bbs_no);
CREATE INDEX IF NOT EXISTS idx_bbs_dd_jobsite_no ON bbs_dd(jobsite_no);
CREATE INDEX IF NOT EXISTS idx_bbs_dd_dd_no ON bbs_dd(dd_no);
CREATE INDEX IF NOT EXISTS idx_bbs_dd_delivery_date ON bbs_dd(dd_delivery_date DESC);
CREATE INDEX IF NOT EXISTS idx_bbs_dd_composite ON bbs_dd(dd_delivery_date DESC, bbs_no);
CREATE INDEX IF NOT EXISTS idx_bbs_dd_jobsite_type ON bbs_dd(jobsite_type);

CREATE TABLE IF NOT EXISTS "TR_Report" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Job_No" TEXT,
    jobsite TEXT,
    order_no BIGINT NOT NULL,
    order_describution TEXT,
    client TEXT,
    del_date DATE,
    ref_no TEXT,
    bbs_po_no TEXT,
    jobsite_type TEXT,
    diameter TEXT,
    wt_ton DOUBLE PRECISION,
    product TEXT,
    grade TEXT,
    pattern TEXT,
    mill_cert TEXT,
    test_cert1 TEXT,
    test_cert2 TEXT,
    supplier TEXT,
    stockist_cert TEXT,
    po_no TEXT,
    rm_dn_no TEXT
);

CREATE INDEX IF NOT EXISTS idx_tr_report_order_no ON "TR_Report"(order_no);
CREATE INDEX IF NOT EXISTS idx_tr_report_job_no ON "TR_Report"("Job_No");
CREATE INDEX IF NOT EXISTS idx_tr_report_del_date ON "TR_Report"(del_date);
CREATE INDEX IF NOT EXISTS idx_tr_report_rm_dn_no ON "TR_Report"(rm_dn_no);
CREATE INDEX IF NOT EXISTS idx_tr_report_jobsite_type ON "TR_Report"(jobsite_type);

CREATE TABLE IF NOT EXISTS "TR_Report_Deduplication" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Order_No" BIGINT NOT NULL,
    "Job_No" TEXT,
    "Jobsite" TEXT,
    "Order_Description" TEXT,
    "Client" TEXT,
    "Del_Date" DATE,
    "Ref_No" TEXT,
    "PO_No" TEXT,
    "Jobsite_Type" TEXT,
    "Wt" DOUBLE PRECISION,
    "Grade" TEXT,
    "rm_dn_no" TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tr_report_dedup_order_no
    ON "TR_Report_Deduplication"("Order_No");
CREATE INDEX IF NOT EXISTS idx_tr_report_dedup_job_no
    ON "TR_Report_Deduplication"("Job_No");
CREATE INDEX IF NOT EXISTS idx_tr_report_dedup_del_date
    ON "TR_Report_Deduplication"("Del_Date" DESC);
CREATE INDEX IF NOT EXISTS idx_tr_report_dedup_rm_dn_no
    ON "TR_Report_Deduplication"("rm_dn_no");
CREATE INDEX IF NOT EXISTS idx_tr_report_dedup_jobsite_type
    ON "TR_Report_Deduplication"("Jobsite_Type");

COMMIT;
